#!/usr/bin/env node

var shield = require('./lib/shield');
var argv = require('optimist')
    .usage('Usage: $0 --label=[string] --value=[string] --file=[filepath] --color=[green/yellowgreen/yellow/red/lightgray/] --scale=[num]')
    .demand(['label','value', 'file'])
    .default('color', 'green')
    .default('scale', 1)
    .argv;

var vendorText = argv.label;
var statusText = argv.value;
var color = argv.color;
var filename = argv.file;
var scale = argv.scale;

shield(vendorText, statusText, color, filename, scale, function(err){
  if (err){
    console.log("Error:");
    console.log(err);
    process.exit(1);
  }
});


